- apps/forms-flow-ai/forms-flow-web/src/components/FOI/ReviewRequest/RequestDescriptionBox.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/ReviewRequest/ReviewRequest.js
Review Comment fixes - 
#77 - replace moment with custom formatDate,
#25 - show/not show OnBehalfOf/ChildDetails based on requestType selection
> Review Comment fixes

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/ReviewRequest/BottomButtonGroup.js
After save request, back button click shows the modal for confirmation. This PR is to fix that issue
> #264 - back button click bug fix

- apps/foi-process/foi-rawrequest-processing.bpmn
1. Changes to claim request through message Event 
2. Capture start Time
3.  Define static candidate group
> foi-flow: 246

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/CustomStyle.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Dashboard.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/dashboard.scss
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/ReviewRequest/ReviewRequestHeader.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/ReviewRequest/reviewrequest.scss
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/ReviewRequest/reviewrequestheader.scss
@divyav-aot 's fixes and #252 - page jumping fixes
> #200, #252 - UX Fixes 

- apps/foi-process/foi-rawrequest-processing.bpmn
Changes to automatically unclaim and claim during change of assignment.
> Changes to automatically unclaim on changing assignment.

- apps/forms-flow-ai/forms-flow-web/src/apiManager/services/FOI/foiRequestServices.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/ReviewRequest/ReviewRequestHeader.js
@divyav-aot : refine it later, if required.
> #200 - Unassigned fix

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/ReviewRequest/ReviewRequestHeader.js
@acoard-aot not sue how this line got missed.
> #200 Unassigned Fix - 

- apps/forms-flow-ai/forms-flow-web/.gitignore
- apps/forms-flow-ai/forms-flow-web/package.json
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Footer/__test__/FOIFooter.test.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Home/__test__/Home.test.js
Unit test for Home and Footer component
> Unit test for Home and Footer component

- foi-start.bat
Changes to merge the files (based on meeting outcome): bug fix
> Dev st 282

- apps/forms-flow-ai/forms-flow-bpm/src/main/java/org/camunda/bpm/extension/keycloak/showcase/CamundaApplication.java
Changes to automate the permissions for service account
> Changes to automate the permissions for service account

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Dashboard.js
Dashboard request type filter issue fixed
> Dashboard request type filter issue fixed

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Dashboard.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/dashboard.scss
> Request Type Filter bug fix

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Dashboard.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/dashboard.scss
> #200 - column spacing fixed

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Dashboard.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/dashboard.scss
#200 - column spacing issue fixed
> #200 - column spacing issue fixed

- apps/forms-flow-ai/forms-flow-web/src/apiManager/services/FOI/foiRequestServices.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/BottomButtonGroup.js
- request-management-api/request_api/services/rawrequestservice.py
#30 - intake state request update issue fixed
> #30 - intake state request update issue fixed

- apps/forms-flow-ai/forms-flow-web/public/index.html
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Dashboard.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/dashboard.scss
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/BottomButtonGroup.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequestHeader.js
- request-management-api/request_api/services/rawrequestservice.py
- Removed assignedTo dropdown from dashboard
- Dropdown arrow click fixed
- Update state after save
> #323 - bug fixes

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/RequestDetails.js
> #330 - Received Date bug fix

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/RequestDetails.js
#330 - received date calculation fixed
> #330 - received date calculation fixed

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/RequestDetails.js
> #330 - start date issue fix

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/RequestDetails.js
Format issue with Received Date is fixed
> Received Date format issue fixed

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
> #303 - fixed build error

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/RequestDetails.js
- apps/forms-flow-ai/forms-flow-web/src/helper/FOI/helper.js
Time Zone added for date conversion
> Time Zone added for date conversion

- apps/forms-flow-ai/forms-flow-web/package.json
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Dashboard.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/AdditionalApplicantDetails.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/ChildDetails.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/OnBehalfOfDetails.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/RequestDetails.js
- apps/forms-flow-ai/forms-flow-web/src/helper/FOI/helper.js
> Date format issue fixed

- apps/forms-flow-ai/forms-flow-web/src/apiManager/services/FOI/foiRequestServices.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Dashboard.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/RequestDetails.js
- apps/forms-flow-ai/forms-flow-web/src/helper/FOI/helper.js
Date format issue - received Date - fixed
> Date format issue - received Date - fixed

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
EmployeeNumber, CorrectionalNumber - json updated
> EmployeeNumber, CorrectionalNumber - json updated

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Dashboard.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/AdditionalApplicantDetails.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/RequestDetails.js
> Merge dev-DV-33 with dev

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/RequestDetails.js
- apps/forms-flow-ai/forms-flow-web/src/constants/FOI/foiComponentConstants.js
- apps/forms-flow-ai/forms-flow-web/src/helper/FOI/helper.js
- due date calculation 
- receivedMode disabled for Unopened requests
> issues fixed - due date calculation - receivedMode disabled 

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Home/Home.js
Added redirect for authenticated user on Home.js
> Redirect authenticated user to dashboard

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Dashboard.js
add condition, show queue only if both rows and assignees are loaded
> Dev rq 465

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequestHeader.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/MinistryAssignToDropdown.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/StateDropDown.js
add default value for ministry dropdown
use helper.isMinistryCoordinator
use foiministrygroupConstants.MINISTRYGROUPS
> remove debugging code

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequestHeader.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/MinistryAssignToDropdown.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/StateDropDown.js
> Dev rq 500

- request-management-api/request_api/models/CloseReasons.py
bug fix - add order by to get close reasons
> Dev rq 681

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Attachments/AttachmentModal.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Attachments/index.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/FileUpload.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/FileUpload.scss
- request-management-api/request_api/services/requestservice.py
> Minor issue fixes

- request-management-api/request_api/services/cdogs_api_service.py
- request-management-api/request_api/services/document_generation_service.py
- request-management-api/tests/restapi/test_fee_api.py
Create pytest test and fix check_template_cached returning false always.
> Create a test for the generate receipt endpoint

- apps/forms-flow-ai/forms-flow-web/src/apiManager/endpoints/index.js
- apps/forms-flow-ai/forms-flow-web/src/apiManager/services/FOI/foiRequestServices.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/BottomButtonGroup.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/MinistryReview.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Attachments/AttachmentModal.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Attachments/attachmentmodal.scss
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Attachments/index.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/ConfirmationModal.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/FileUpload.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/FileUpload.scss
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/confirmationmodal.scss
- apps/forms-flow-ai/forms-flow-web/src/constants/FOI/statusEnum.js
- request-management-api/request_api/resources/foiflowmasterdata.py
- Replace attachment
- Duplicate file name validation
- Style changes for Error message
> US #782 changes

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Attachments/AttachmentModal.js
> Dev rq 779

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/MinistryReview.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Comments/DisplayComments.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Comments/Input.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Comments/InputField.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Comments/index.js
1. Close button click
2. Tab change
3. Browser refresh/navigate away from browser
> Navigate away from Comments(#785)

- request-management-api/request_api/services/events/state.py
Changes to rename Archived to Open for system comments - Merge.
> Changes to rename Archived to Open for comments.

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Attachments/AttachmentModal.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Attachments/index.js
2. fix css for save button on rename modal
> 1. disable delete for personal attachment

- request-management-api/request_api/services/documentservice.py
> Code merge Integration fix

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/utils.js
- request-management-api/request_api/schemas/foirequestwrapper.py
- request-management-api/request_api/services/foirequest/requestservicebuilder.py
- request-management-api/request_api/services/foirequest/requestservicecreate.py
- request-management-api/request_api/services/rawrequest/rawrequestservicegetter.py
- request-management-api/request_api/services/rawrequestservice.py
1. [ ] Tested For Personal Request with Child another Personal - with state transition from Unopened(Angular app submission) to CFR- AS IAO Login
2. [ ] Tested for General Request  -- with state transition from Unopened(Angular app submission) to CFR - AS IAO Login
3. [ ] Tested For Personal Request with Child another Personal - with state transition from _Intake In progress to CFR_- AS IAO Login ; FOI Flow IAO Submission
4. [ ] Tested for General Request  -- with state transition from _Intake In progress to CFR_ - AS IAO Login; FOI Flow IAO Submission
5. [ ] Tested for General to Personal Request update ; with and without - Child and Other Person Info
6. [ ] Tested With Open to CFR then to Closed, with reopen
7. [ ] Tested Comments
8. [ ] Tested with state transitions and updates for …
> PR - Additional Personal Info. Issue with Backend and Front End

- request-management-api/request_api/services/rawrequest/rawrequestservicegetter.py
1.  Tested Personal FOI requests with and without PHN and DOB as Intake. Checked 
2. Tested Personal FOI Requests submission from DEV Frontend Application of FOI Req. Submission - DOB is getting captured. No PHN from Public app
3. Tested regular General FOI requests - state transition as Intake
4. Tested Conversion from General to Personal as Intake - PHN is persisting - Refer #1089
5. Tested StartDate Enddate issue - #1098 
6. Tested #1073
> #1089  PHN missing issue for intake

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Header/NotificationPopup/NotificationList/NotificationList.js
Tested notifications for request assignment and watching requests.
Tested dismiss notifications.
> Pop up loading issue fix

- apps/forms-flow-ai/forms-flow-web/src/apiManager/services/FOI/foiRequestServices.js
- apps/forms-flow-ai/forms-flow-web/src/apiManager/services/FOI/foiServicesUtil.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Header/NotificationPopup/NotificationList/NotificationList.js
Tested creating new request - both personal and general. Made sure all required fields are persisting data and non-mandatory fields are persisting with and with out data.
Tested state transitions and assignments, Watchers - INTAKE IN PROGRESS to CFR.
Tested login with MINISTRY VIEW.
Tested attachments, Comments.
Tested notifications for request assignment and watching requests.
Tested dismiss notifications.
Tested Navigating from notifications.
> Navigating from Notifications with fix

- apps/forms-flow-ai/forms-flow-web/src/apiManager/services/FOI/foiRequestServices.js
- apps/forms-flow-ai/forms-flow-web/src/apiManager/services/FOI/foiServicesUtil.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Header/FOIHeader.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Header/NotificationPopup/NotificationList/NotificationList.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Header/NotificationPopup/NotificationPopup.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Header/NotificationPopup/notificationpopup.scss
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Header/foiheader.scss
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/MinistriesCanvassed/MinistriesCanvassed.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/MinistriesCanvassed/MinistriesCanvassed.test.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/MinistriesCanvassed/ministriescanvassed.scss
- request-management-api/request_api/models/FOIMinistryRequests.py
- request-management-api/request_api/services/rawrequest/rawrequestservicegetter.py
Tested creating new request - both personal and general. Made sure all required fields are persisting data and non-mandatory fields are persisting with and with out data.
Tested state transitions and assignments, Watchers - INTAKE IN PROGRESS to CFR.
Tested login with MINISTRY VIEW with Minis. COORDIANTOR l and did state transitions.
Tested attachments, Comments.
Tested notifications for request assignment and watching requests.
Tested dismiss notifications.
Tested Navigating from notifications (#1343 ).
> Navigating from Open Notifications

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Dashboard.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/MinistryDashboard.js
1. Fix default sorting order (Current State) in ministry queue
2. Fix sorting order for Applicant Name in IAO queue
> Dev rq 1088

- request-management-api/request_api/models/FOIMinistryRequests.py
Description: Whitelist/Blacklist of statuses to be considered for reminder notifications of CFR and LDD
ACs: All Passed
Sanity Tests Executed:
1. Opening a request.
2. Updating the request
3. Add comment and replies
4. Change the workflow of request (Intake In Progress -> Open -> CFR -> Ministry Sign Off) , (Intake In Progress -> Closed)
5. Notifications on assignment
6. System generated comments for state transition
> Dev st 1329 - Whitelist/Blacklist of statuses to be considered for reminder notifications of CFR and LDD

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/ExtensionDetails/ExtensionDetailsBox.js
Description: Whitelist/Blacklist of statuses to be considered for reminder notifications of CFR and LDD
ACs: All Passed
Sanity Tests Executed:
Opening a request.
Updating the request
Add comment and replies
Change the workflow of request (Intake In Progress -> Open -> CFR -> Ministry Sign Off) , (Intake In Progress -> Closed)
Notifications on assignment
System generated comments for state transition
> Dev - Whitelist/Blacklist of statuses to be considered for reminder notifications of CFR and LDD

- request-management-api/request_api/services/extensionservice.py
Extension denied date issue fixed (#882 )
> Extension denied date issue fixed

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/BottomButtonGroup/utils.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/ConfirmationModal/util.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/StateDropDown.js
Fix state open cancel issue and Redirect AssignedTo issue - Personal request
> Fix state open cancel issue and Redirect AssignedTo issue

- request-management-api/requirements.txt
> Dev st 906

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/IAO/Queue.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/MinistryDashboard.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/dashboard.scss
> 1. fix new data issue

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/Divisions/DivisionalStages.js
Fix for Updates to Divisional Tracking not displaying until saved issue.
Tested Divisional Tracking.
> Fix for #1404

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Header/FOIHeader.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Header/NotificationPopup/NotificationList/NotificationList.js
Description:
Fix for not displaying User Name of who made change/authored updates on notifications in Dashboard view.
> Fix for notification author name

- request-management-api/request_api/utils/redissubscriber.py
Debug logs for api cluster setup on ws calls.
> Dev st 1473

- apps/forms-flow-ai/forms-flow-bpm/src/main/resources/processes/foi-duedate-reminder.bpmn
> changes to verify bpm build

- apps/forms-flow-ai/forms-flow-bpm/src/main/resources/application-foi.yaml
Changes of bpm upgrade to 7.15
> Changes of upgrade.

- request-management-api/request_api/models/FOIRawRequests.py
- request-management-api/request_api/services/auditservice.py
Description:
In DEV while Camunda was down, the updated_at fields were null and that caused the date conversion in API to throw error.
So changed the field taken to display Request Description history from updated_at to created_at field.
> Displaying date field changed

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/IAO/AdvancedSearch/DataGridAdvancedSearch.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/IAO/columns.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Ministry/AdvancedSearch/DataGridAdvancedSearch.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Ministry/Queue.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/utils.js
- request-management-api/request_api/models/FOIMinistryRequests.py
- request-management-api/request_api/models/FOIRawRequests.py
- request-management-api/request_api/services/dashboardservice.py
1. format assignedto on backend - fullname/group name
2. sorting assignedto will apply to both fullname and group name now
3. fix sorting issue on LDD  & Days left - IAO queue
4. fix wrong received date issue - IAO queue
5. Nick's updates foiheader.scss
> Dev rq 1688 1530

- apps/forms-flow-ai/forms-flow-web/src/constants/FOI/enum.js
does not have ms office installed on it
> hardcode excel and word file types since github actions vm

- apps/forms-flow-ai/forms-flow-web/public/service-worker.js
Description:
Issue : Critical vulnerability displayed by Sonar cloud in Service Worker file: **Verify the origin of the received message.**
Fix : Added a check for verifying origin URL.
> Sonar cloud security issue fix

- request-management-api/request_api/models/FOIRawRequests.py
bug fix: make receivedDate search work for online form submissions
> bug fix: make receivedDate search work for online form submissions

- apps/forms-flow-ai/forms-flow-web/src/apiManager/services/FOI/foiRequestServices.js
- apps/forms-flow-ai/forms-flow-web/src/apiManager/services/FOI/foiServicesUtil.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/AxisDetails/AxisSyncModal.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- apps/forms-flow-ai/forms-flow-web/src/constants/FOI/axisSyncDisplayFields.js
Axis sync fix for on behalf of.
**ACs: All Passed**
**Sanity Tests Executed:**
Tested creating new request - both personal and general. Made sure all required fields are persisting data and non-mandatory fields are persisting with and with out data.
Tested state transitions and assignments, Watchers - INTAKE IN PROGRESS to CFR.
Tested login with MINISTRY VIEW with Minis. COORDIANTOR l and did state transitions.
Tested submission of  PERSONAL and GENERAL Requests from Angular App. LOCALLY.
Tested attachments, comments, notifications.
> Axis sync fix for on behalf of

- request-management-api/request_api/models/FOIMinistryRequests.py
- request-management-api/request_api/models/FOIRawRequestComments.py
- request-management-api/request_api/models/FOIRawRequestDocuments.py
- request-management-api/request_api/models/FOIRawRequestNotificationUsers.py
- request-management-api/request_api/models/FOIRawRequestNotifications.py
- request-management-api/request_api/models/FOIRawRequestWatchers.py
- request-management-api/request_api/models/FOIRawRequests.py
- request-management-api/request_api/models/FOIRequestComments.py
- request-management-api/request_api/models/FOIRequestExtensions.py
- request-management-api/request_api/models/FOIRequestNotificationUsers.py
- request-management-api/request_api/models/FOIRequestNotifications.py
- request-management-api/request_api/models/FOIRequestTeams.py
- request-management-api/request_api/models/FOIRequestWatchers.py
- request-management-api/request_api/models/OperatingTeams.py
Detail: Explicit session closure for select statements.
Sanity:
1. Create a request
2.  Watch/Unwatch request
3.  Push Notifications
4. Reminder Notifications
5.  Update Request
6.  State transition Intake In Progress -> Open -> Call For Records
> Explicit connection handling for select statements.

- request-management-api/wsgi.py
> Changes to check token expiry

- request-management-api/request_api/__init__.py
- request-management-api/request_api/resources/__init__.py
- request-management-api/request_api/utils/redispublisher.py
- request-management-api/wsgi.py
> Dev st 1891

- .github/workflows/katalon-ci.yaml
#	.github/workflows/katalon-ci.yaml
> merge yaml to main to test running cron job

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/ChildDetails.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/OnBehalfOfDetails.js
Remove 'Attached Documents' text in 'CHILD DETAILS' and 'ON BEHALF OF DETAILS'.
> Remove 'Attached Documents' text

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequestHeader/index.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequestHeader/utils.js
Tested Add request
State change
Ministry view
Dashboards
> Display 'Ministry Team' name in Assigned in IAO request view

- request-management-api/request_api/__init__.py
- request-management-api/request_api/models/FOIRawRequests.py
- request-management-api/request_api/resources/__init__.py
- request-management-api/request_api/resources/foiaudit.py
- request-management-api/request_api/resources/ops.py
- request-management-api/request_api/services/auditservice.py
- request-management-api/request_api/services/foirequest/requestserviceministrybuilder.py
- request-management-api/request_api/services/notifications/notificationuser.py
- request-management-api/request_api/utils/util_logging.py
Sanity Checks:
1. Create a new request with sync from axis
2.  Watch/Unwatch
3. Add comments
4. State transition
5.  Update the request
6. Push notifications.
> Sonar Cloud fixes.

- request-management-api/request_api/models/FOIRawRequests.py
Sanity Checks:
Create a new request with sync from axis
Watch/Unwatch
Add comments
State transition
Update the request
Push notifications.
Search with criteria
> Fix exception on search.

- request-management-api/request_api/models/FOIRawRequests.py
- request-management-api/request_api/resources/__init__.py
- request-management-api/request_api/resources/foirequest.py
- request-management-api/request_api/resources/request.py
- request-management-api/request_api/services/events/extension.py
- request-management-api/request_api/services/events/legislativedate.py
- request-management-api/request_api/services/external/keycloakadminservice.py
- request-management-api/request_api/services/notificationservice.py
- request-management-api/request_api/services/rawrequestservice.py
- request-management-api/request_api/services/rest_service.py
- request-management-api/request_api/utils/cache.py
- request-management-api/update_failed_gl_codes_cli.py
Sanity Checks:
- Create a new request with sync from axis
- Watch/Unwatch
- Add comments
- State transition
- Update the request
- Push notifications.
- Search with criteria
> Sonar Cloud Fixes

- request-management-api/request_api/models/FOIMinistryRequests.py
tested moving to open stage, then assigning back to intake team
> only show open requests of type general in intake queue

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/IAO/AdvancedSearch/SearchComponent.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Ministry/AdvancedSearch/SearchComponent.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/utils.js
change advanced search to filter by
> do not show red on cfr overdue

- request-management-api/request_api/models/FOIMinistryRequests.py
- request-management-api/request_api/models/FOIRawRequests.py
one column is missing in base query
> bug fix for dashboard:

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/MinistryReviewTabbedContainer.scss
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/foirequest.scss
- apps/forms-flow-ai/forms-flow-web/src/styles.scss
**Description :** 
Contains updates to scrollbar for avoiding the margin for no banner scenario.
> Scrollbar margin update for no banner scenario (#2069)

- request-management-api/request_api/models/FOIMinistryRequests.py
Not apply group filter for watched queue #2092
> Bug fix for watched queue #2092

- request-management-api/request_api/models/FOIRequestExtensions.py
Changes to do delete of extensions with attachments
Technical change to soft delete of extensions
Change the sorting order of program areas.
Sanity Checks
Create a new request
Update an request
Sync with axis
Watch/Unwatch request
Add comments
State transitions Intake in Progress -> Open -> CFR
> Change of argument for ministry ID

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/ExtensionDetails/AddExtensionModal.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/ExtensionDetails/DeleteExtensionModal.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/ExtensionDetails/ExtensionsTable.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/foirequest.scss
- request-management-api/request_api/models/FOIRequestExtensions.py
and refreshing attachments and comments on extension save/delete
> fix extensions actions not being visible, extensions out of order,

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/RequestDescriptionBox.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/utils.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/MinistriesList.js
- request-management-api/request_api/models/FOIRawRequests.py
- request-management-api/request_api/resources/request.py
- request-management-api/request_api/services/rawrequest/rawrequestservicegetter.py
- request-management-api/request_api/services/rawrequestservice.py
Validation added in the FE
Validation for AXIS Request ID added in the BE
> Duplicate request issue - Added validation

- request-management-api/request_api/models/FOIMinistryRequests.py
add same fix for FOIMinistryRequests class which advanced search and ministry queue uses
> add same fix for ministry requests

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Ministry/AdvancedSearch/enum.js
- request-management-api/request_api/models/FOIMinistryRequests.py
- request-management-api/request_api/models/FOIRawRequests.py
Bug fix: 
1. search not Axis ID not working sometimes
2. assignee search not working in ministry advanced search #2145
> Bug fix for #2145 and search axis id in iao queue

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Ministry/AdvancedSearch/SearchComponent.js
**Description :** 
Clear All Filters not clearing up the "On Time" Request Status Checkbox (Advanced Search for Ministry)#2134
Tested #2134.
> Clear All Filters not clearing up the "On Time" Request Status Checkbox (Advanced Search for Ministry) #2134

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/IAO/AdvancedSearch/SearchComponent.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Ministry/AdvancedSearch/SearchComponent.js
- request-management-api/request_api/services/extensionservice.py
> PB - Pending and Search keyword Trim()

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/RequestDetails.js
set start date to received date
> work around for chrome & edge bug:

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequestHeader/index.js
Ministry list removed from IAO watcher list.
> IAO Watcher List updated

- request-management-api/request_api/models/FOIMinistryRequests.py
> exclude "on hold" requests for overdue in advanced search

- apps/forms-flow-ai/forms-flow-web/src/apiManager/services/FOI/foiCFRFormServices.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/MinistryReview.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/CFRForm/index.tsx
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/ConfirmationModal/confirmationmodal.scss
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/ConfirmationModal/index.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/ConfirmationModal/util.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/FileUpload/FileUpload.scss
- apps/forms-flow-ai/forms-flow-web/src/modules/FOI/foiRequestsReducer.js
- request-management-api/request_api/services/cfrfeeservice.py
- request-management-api/request_api/services/events/state.py
> Dev nk 2258

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/CustomFooter.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/IAO/AdvancedSearch/DataGridAdvancedSearch.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/IAO/Queue.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Ministry/AdvancedSearch/DataGridAdvancedSearch.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/Ministry/Queue.js
only call advanced search if click the advanced search button
> Performance improvement:

- apps/forms-flow-ai/forms-flow-web/src/apiManager/services/FOI/foiCFRFormServices.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/CFRForm/index.tsx
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/CFRForm/types.ts
- request-management-api/request_api/services/cfrfeeservice.py
> Revert "Revert "Dev nk 2258""

- apps/forms-flow-ai/forms-flow-web/src/apiManager/services/FOI/foiRequestServices.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/AxisDetails/AxisDetails.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/AxisDetails/AxisSyncModal.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/ChildDetails.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/OnBehalfOfDetails.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/utils.js
- apps/forms-flow-ai/forms-flow-web/src/constants/FOI/axisSyncDisplayFields.js
**Description :** 
Additional Application Details getting cleared off after AXIS Sync - Personal Requests #2184.
**Tests Executed :** 
Tested creating request and syncing from axis.
Tested request from form submission app and tried syncing requests.
Tested state changes.
Tested Axis Banner.
> Additional Application Details getting cleared off after AXIS Sync - Personal Requests #2184

- forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
> Fix for #2484

- request-management-api/request_api/models/FOIMinistryRequestDocuments.py
- request-management-api/request_api/services/documentservice.py
Only the newly uploaded files should be sent to user even if the request is changed from Fee Estimate to On hold multiple times#2526.
> Only the newly uploaded files should be sent to user even if the request is changed from Fee Estimate to On hold multiple times#2526

- apps/forms-flow-ai/forms-flow-web/package.json
- apps/forms-flow-ai/forms-flow-web/src/apiManager/endpoints/index.js
- apps/forms-flow-ai/forms-flow-web/src/apiManager/services/FOI/foiOSSServices.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIBaseRouting.jsx
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIDocumentViewRouting.jsx
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/AttachmentViewer/index.scss
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/AttachmentViewer/index.tsx
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/AttachmentViewer/types.ts
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Attachments/attachments.scss
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Attachments/index.js
- request-management-api/request_api/resources/foiflowmasterdata.py
- request-management-api/requirements.txt
-  [x]  Tested Attachment Upload and View on Browser functionality
-  [x] File extensions like .XLS, XLSX, DOC, DOCX, PDF, JPG, JPEG, PNG are viewable on browser tab, after clicking attachment title or "View" from ellipsis
-  [x]  EML and MSG files are not viewable on browser, hence disabled the title
-  [x] Used new S3 Presigned URL approach for S3 rather than existing S3 Signature fetch approach.
-  [x] Tested usual state transitions and file uploads using ministry user
Note : Need to confirm personal file are not viewable for ministry users once deployed to DEV, since local check is difficult. Will confirm before PR to Main.
> View attachment PR to DEV

- forms-flow-web/src/components/FOI/customComponents/Attachments/index.js
- forms-flow-web/src/constants/FOI/statusEnum.js
- request-management-api/request_api/services/email/templates/templateconfig.py
- request-management-api/request_api/services/emailservice.py
> attachment category updated. disable for ministry.

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Attachments/AttachmentFilter.tsx
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Comments/CommentFilter/index.tsx
set width for attachment and comment filter
> Dev rq 1974 2470

- request-management-api/request_api/resources/foirequest.py
- request-management-api/request_api/resources/request.py
- request-management-api/request_api/services/events/assignment.py
- request-management-api/request_api/services/eventservice.py
Note : Autor fresh to Comments Tab is not done for self assignments , highlighted to business and reverted that it can be done separately whenever required. But more things are in priority for dev test like, UnOpened requests checks etc.
> #2471 System generated comments for Assignments

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Attachments/AttachmentModal.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/Attachments/index.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/FileUpload/FileUpload.scss
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/customComponents/FileUpload/index.js
- apps/forms-flow-ai/forms-flow-web/src/constants/FOI/statusEnum.js
Add attachment modal with tag #2489
> Dev rq 2489

- apps/forms-flow-ai/forms-flow-ai-web/src/components/Form/Item/Edit.js
- apps/forms-flow-ai/forms-flow-ai-web/src/helper/helper.js
- apps/forms-flow-ai/forms-flow-bpm/src/main/resources/processes/foi-initial-payment-submission.bpmn
> updated the form submission for anonymous user

- forms-flow-web/src/components/FOI/customComponents/CFRForm/index.tsx
- forms-flow-web/src/modules/FOI/foiRequestsReducer.js
fix unable to send back to iao during 1st version clarification
> remove reduce so cfrform state gets reset on opening new request

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/AxisDetails/AxisSyncModal.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/utils.js
- request-management-api/request_api/models/FOIMinistryRequests.py
Description : 
Fixed issue in syncing Multiple Public Body Extensions of Same Type #1845.
> Sync Multiple Public Body Extensions of Same Type (#1845)

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/AxisDetails/AxisSyncModal.js
- request-management-api/request_api/models/FOIMinistryRequests.py
- request-management-api/request_api/models/FOIRequestExtensions.py
- request-management-api/request_api/services/extensionservice.py
Description : 
Backend Task : Deactivate previous extensions when new extension is manually added or deleted in FOI system.
Fix for Extension comments are generated even if axis updates for fields other than extensions are synced up.
> Contains #2737 & #2751

- request-management-api/request_api/services/email/templates/templateconfig.py
Merging without approval for testing the payment receipt.
> Outstanding email subject and attachment category updates

- request-management-api/migrations/versions/9bb86f534044_.py
- request-management-api/request_api/services/paymentservice.py
Merging to test in dev-marshal
> receipt template - migration script

- request-management-api/request_api/models/FOIRequestExtensions.py
- request-management-api/request_api/models/FOIRequestNotifications.py
- request-management-api/request_api/resources/foiextension.py
- request-management-api/request_api/services/events/extension.py
- request-management-api/request_api/services/eventservice.py
- request-management-api/request_api/services/extensionservice.py
Description: 
Duplicate comments getting generated while syncing extensions from Axis (#2759)
> Duplicate comments getting generated while syncing extensions from Axis (#2759)

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/AxisDetails/AxisSyncModal.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
Description:
Banner fix and Manually added same extension fix. Removed check for approvednoofdays.
> Banner and Manually added same extension fix

- apps/forms-flow-ai/forms-flow-bpm/src/main/resources/processes/foi-initial-payment-submission.bpmn
- apps/forms-flow-ai/forms-flow-bpm/src/main/resources/processes/foi-request-processing.bpmn
- forms-flow-web/src/apiManager/endpoints/index.js
- forms-flow-web/src/apiManager/services/FOI/foiCFRFormServices.js
- request-management-api/request_api/resources/fee.py
- request-management-api/request_api/resources/foicfrfee.py
- request-management-api/request_api/services/requestservice.py
- request-management-api/request_api/services/workflowservice.py
API changes to call WF with paymentstatus CANCELLED
WF updates to keep the instance ready for the above task
> Expiry of payment link when a new CFR Form is approved

- apps/forms-flow-ai/forms-flow-bpm/src/main/resources/processes/foi-initial-payment-submission.bpmn
- forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- request-management-api/request_api/services/documentservice.py
- request-management-api/request_api/services/events/payment.py
1. Notification text date change
2. WF changes to stop the automated state change if correspondence
3. paymentexpiry link update
> send email - updated

- apps/forms-flow-ai/forms-flow-bpm/src/main/resources/processes/foi-initial-payment-submission.bpmn
- request-management-api/request_api/resources/fee.py
- request-management-api/request_api/resources/foirequest.py
- request-management-api/request_api/services/requestservice.py
- request-management-api/request_api/services/workflowservice.py
1. Removed state change from fee.py for the PAID status
2. Created new API endpoint for state update
3. Call the new API from the WF based on servicekey != "correspondence"
> Removed state update from fee.py

- apps/forms-flow-ai/forms-flow-bpm/src/main/resources/processes/foi-initial-payment-submission.bpmn
- request-management-api/request_api/resources/foirequest.py
- request-management-api/request_api/services/paymentservice.py
- request-management-api/request_api/services/requestservice.py
merging the PR as it is for debugging the issue.
> added debug comments, fixed few runtime errors

- request-management-api/request_api/resources/foirequest.py
- request-management-api/request_api/services/requestservice.py
merging as it is for debugging.
> removed unnecessary codes

- apps/forms-flow-ai/forms-flow-bpm/src/main/resources/processes/foi-initial-payment-submission.bpmn
- request-management-api/request_api/resources/foirequest.py
- request-management-api/request_api/schemas/foirequestwrapper.py
- request-management-api/request_api/services/requestservice.py
> state change updated

- apps/forms-flow-ai/forms-flow-bpm/src/main/resources/processes/foi-initial-payment-submission.bpmn
- request-management-api/request_api/services/foirequest/requestservicegetter.py
test float with 2 decimal points
> float with 2 decimal points. WF updates - remove debug points.

- apps/forms-flow-ai/forms-flow-bpm/src/main/resources/processes/foi-email-processing.bpmn
- apps/forms-flow-ai/forms-flow-bpm/src/main/resources/processes/foi-initial-payment-submission.bpmn
- request-management-api/request_api/resources/fee.py
> updated WF and BE to get the proper template

- forms-flow-web/src/apiManager/services/FOI/foiCFRFormServices.js
- forms-flow-web/src/apiManager/services/FOI/foiCorrespondenceServices.js
- forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/MinistryReview.js
- forms-flow-web/src/components/FOI/customComponents/CFRForm/index.tsx
- request-management-api/request_api/auth.py
- request-management-api/request_api/resources/applicantcorrespondence.py
add iao auth check for correspondence log api
fix correspondence log front end cache issue
> show version number for cfr form

- request-management-api/request_api/resources/foirequest.py
Bug fix: api error when changing assignee
> Dev Marshal 2702 - bug fix

- forms-flow-web/src/components/FOI/FOIRequest/AxisDetails/AxisSyncModal.js
- forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- forms-flow-web/src/components/FOI/FOIRequest/utils.js
- forms-flow-web/src/constants/FOI/enum.js
- request-management-api/migrations/versions/4bd9d39a052e_.py
- request-management-api/request_api/models/FOIMinistryRequests.py
- request-management-api/request_api/models/FOIRequestComments.py
- request-management-api/request_api/models/FOIRequestExtensions.py
- request-management-api/request_api/models/FOIRequestNotifications.py
- request-management-api/request_api/models/samplequeries/businessteamdata.sql
- request-management-api/request_api/models/samplequeries/findcolumnvalue.sql
- request-management-api/request_api/resources/foiextension.py
- request-management-api/request_api/services/events/extension.py
- request-management-api/request_api/services/eventservice.py
- request-management-api/request_api/services/extensionservice.py
- request-management-api/request_api/utils/enums.py
Extension changes
Amalgamate Central and Business team
> merged changes from main branch

- forms-flow-web/src/apiManager/services/FOI/foiCFRFormServices.js
- forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/MinistryReview.js
- forms-flow-web/src/components/FOI/customComponents/CFRForm/index.tsx
The "Click "i" for more details" bubble in the CFR Form page is cut off / not visible #2948
Update F.E to asynchronously call APIs in Request page #2935
> #2935 and #2948

- forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/index.tsx
- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/util.tsx
- forms-flow-web/src/modules/FOI/foiRequestsReducer.js
disable add new correspondence button in fee estimate stage and after balance remaining is zero disable contact applicant for personal requests
> move template disabled logic to helper function

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/RequestDetails.js
- request-management-api/request_api/models/FOIRawRequests.py
- request-management-api/request_api/services/foirequest/requestservicegetter.py
- request-management-api/request_api/services/rawrequest/rawrequestservicegetter.py
Description:
Fix for Backdating Closed Date #2994
> Backdating Closed Date #2994

- apps/forms-flow-ai/forms-flow-ai-web/src/components/Form/Item/Submission/Item/PublicEdit.js
- apps/forms-flow-ai/forms-flow-ai-web/src/containers/SubmissionError.jsx
- forms-flow-web/src/components/FOI/customComponents/CFRForm/index.tsx
Added few debug lines to test in dev-marshal
> Fixes related to Token expired

- request-management-api/request_api/models/FOIRequestCFRFees.py
- request-management-api/request_api/services/cfrfeeservice.py
- request-management-api/request_api/services/foirequest/requestservicegetter.py
Changes to consider the approved CFR Form for payment.
Sanity
1. Create Request
2. Watch/Unwatch Request
3. Add Comment
4. Upload Files
5. State Transistion
6. Email
> Dev marshal st 2955

- apps/forms-flow-ai/forms-flow-bpm/src/main/resources/processes/foi-request-processing.bpmn
- request-management-api/request_api/models/FOIRawRequests.py
- request-management-api/request_api/services/external/bpmservice.py
- request-management-api/request_api/services/workflowservice.py
Changes to verify the presence of FOI-specific IDs in WF & sync.
> Sync WF instance.

- request-management-api/request_api/services/workflowservice.py
merging this PR as its for testing.
> added few debug lines

- request-management-api/request_api/services/workflowservice.py
> pushed few more debug statements

- request-management-api/request_api/models/FOIRequests.py
- request-management-api/request_api/services/foirequest/requestservicebuilder.py
- request-management-api/request_api/services/foirequest/requestserviceupdate.py
> added few more debug lines

- request-management-api/request_api/services/notifications/duecalculator.py
- request-management-api/request_api/services/requestservice.py
Changes to perform new due date based on payment.
> Dev st 2960

- request-management-api/request_api/email_templates/fee_payment_confirmation_full.html
- request-management-api/request_api/email_templates/fee_payment_confirmation_half.html
- request-management-api/request_api/email_templates/fee_payment_confirmation_outstanding.html
Changes to support date formatting in templates.
> Template changes for date formattting.

- .github/workflows/forms-flow-ai-web-cd.yml
Since the dev and test is not ready for the new environment, the "Watch new rollout (trigger by image change in Openshift)" part has been commented out. Once the environment is ready with deployment config, this will be uncommented.
> Git actions updated

- forms-flow-web/src/components/FOI/FOIRequest/BottomButtonGroup/index.js
- request-management-api/request_api/models/FOIMinistryRequests.py
- request-management-api/request_api/models/FOIRequestStatus.py
- request-management-api/request_api/services/requestservice.py
Changes to ensure due date calculation does not happen multiple time within a day.
Sanity:
1. Create a request
2. State Transition till On Hold
3. Verification of email 
4. Verification of comments
> Fix for 3917. Changes to avoid multiple due date calculation.

- apps/forms-flow-ai/forms-flow-ai-web/Dockerfile
- apps/forms-flow-ai/forms-flow-ai-web/Dockerfile.local
Changes to resolve the logout issue in KC v7.16.x
Sanity:
- Login to application
- Logout successfully (Session Invalidation)
> Changes to upgrade keycloak-js to 20.0.2

- forms-flow-web/src/components/FOI/customComponents/Records/index.js
batch download original and converted
remove duplicates from batch download
> download original and PDF for converted files

- request-management-api/request_api/services/recordservice.py
or deleting a duplicate from another division
> fix edge case with deleting original with multiple divisions

- forms-flow-web/src/components/FOI/customComponents/Records/index.js
- request-management-api/request_api/services/recordservice.py
or deleting a duplicate from another division
> fix edge case with deleting original with multiple divisions 

- apps/forms-flow-ai/forms-flow-ai-web/Dockerfile
- apps/forms-flow-ai/forms-flow-ai-web/Dockerfile.local
- apps/forms-flow-ai/forms-flow-bpm/pom-docker.xml
- forms-flow-web/package-lock.json
- forms-flow-web/package.json
Changes to support migration [KC - v7.16.x]
Sanity:
1. Login to applications
2. Logout
3. Create Request
4. State Transition
5.  Payment Email
> Dev st 3002

- forms-flow-web/src/components/FOI/customComponents/RequestRestriction.js
- request-management-api/request_api/resources/foirequest.py
- request-management-api/request_api/utils/util.py
> Dev iao restricted fixes

- request-management-api/request_api/services/recordservice.py
Acceptance Criteria - Met All.
Unit Testing
Create Request
State transition 
Upload records for conversion and dedupe
> Changes to pass createdby to event queue.

- request-management-api/request_api/resources/foirecord.py
- request-management-api/request_api/schemas/foirecord.py
- request-management-api/request_api/services/recordservice.py
Updated uploader name for attachments of record  #3162
> Updated uploader name for attachments of record  #3162

- forms-flow-web/src/apiManager/services/FOI/foiMasterDataServices.js
- forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/RequestHeader.js
- forms-flow-web/src/components/FOI/customComponents/Comments/index.js
- forms-flow-web/src/components/FOI/customComponents/ConfirmModalWatcher.js
Removed debug codes in Frontend.
> Removed debug codes

- request-management-api/request_api/services/cacheservice.py
- request-management-api/request_api/utils/enums.py
Description:
Adde Subject codes API to Caching API for nightly caching.
> Subject codes API added to Caching API

- request-management-api/request_api/resources/foiassignee.py
- request-management-api/request_api/utils/enums.py
Commented out caching for other foiassignees related apis to avoid issues with assignee list.
> Commented out caching for other foiassignees related apis

- forms-flow-web/src/components/FOI/customComponents/Attachments/AttachmentModal.js
- forms-flow-web/src/components/FOI/customComponents/Attachments/index.js
- forms-flow-web/src/components/FOI/customComponents/ConfirmationModal/index.js
- forms-flow-web/src/constants/FOI/statusEnum.js
- request-management-api/request_api/resources/foiassignee.py
Add missing attachment categories:
Response -> Review
Sign off -> Review
> Bug fix: add missing attachment categories

- apps/forms-flow-ai/forms-flow-bpm/src/main/resources/processes/foi-cache-refresh.bpmn
Changes to cache refresh process to improve the performance of dashboard.
Unit Testing:
1. Acceptance Criteria
2. Create request till email.
> Cache refresh changes

- request-management-api/request_api/models/FOIRequestTeams.py
Changes to skip overriding of default assignment (for flex inclusion)
> Changes to skip default assignment to Flex team.

- forms-flow-web/src/components/FOI/customComponents/MinistriesList.js
> #3391 changed checkmark id

- forms-flow-web/src/components/FOI/customComponents/CFRForm/index.tsx
For CFR form automation added id for save button
> #3474 Added button id for CFR forms

- forms-flow-web/src/apiManager/endpoints/index.js
- forms-flow-web/src/apiManager/services/FOI/foiOSSServices.js
- forms-flow-web/src/components/FOI/FOIRequest/BottomButtonGroup/index.js
- forms-flow-web/src/components/FOI/FOIRequest/ExtensionDetails/utils.js
- forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/BottomButtonGroup.js
- forms-flow-web/src/components/FOI/customComponents/Attachments/index.js
- request-management-api/request_api/resources/foiflowmasterdata.py
- request-management-api/request_api/services/documentservice.py
- request-management-api/request_api/services/external/storageservice.py
- request-management-api/request_api/utils/enums.py
> change all file upload to use presigned url

- forms-flow-web/src/apiManager/endpoints/index.js
- forms-flow-web/src/apiManager/services/FOI/foiOSSServices.js
- forms-flow-web/src/components/FOI/FOIRequest/BottomButtonGroup/index.js
- forms-flow-web/src/components/FOI/FOIRequest/ExtensionDetails/utils.js
- forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/BottomButtonGroup.js
- forms-flow-web/src/components/FOI/customComponents/Attachments/index.js
- forms-flow-web/src/components/FOI/customComponents/CFRForm/index.tsx
- request-management-api/migrations/versions/e0cdabe946cc_PSE_Divisions_2.py
- request-management-api/request_api/resources/foiflowmasterdata.py
- request-management-api/request_api/services/documentservice.py
- request-management-api/request_api/services/external/storageservice.py
- request-management-api/request_api/utils/enums.py
tested:
attachment log upload
state change upload by ministry and iao
extension upload
contact applicant upload
payment receipt upload
> change all file upload to s3 presigned

- forms-flow-web/src/constants/FOI/enum.js
- request-management-api/migrations/versions/5ef3541c7524_IAO_realignment.py
- request-management-api/request_api/models/FOIRequestTeams.py
- request-management-api/request_api/services/external/keycloakadminservice.py
- request-management-api/request_api/utils/enums.py
add new teams to enum
code changes to show all iao in assignee drop down, with mapped team at the top
> migration script for iao realignment

- testing/foi-qa-automation/Test Suites/foi-test.ts
> #3587 Updated test suite

- forms-flow-web/src/apiManager/endpoints/index.js
- forms-flow-web/src/apiManager/services/FOI/foiRecordServices.js
- forms-flow-web/src/components/FOI/customComponents/Records/index.js
- forms-flow-web/src/components/FOI/customComponents/Records/util.js
- notification-manager/notification_api/io/message/processor/notificationprocessor.py
- notification-manager/notification_api/io/message/schemas/notification.py
- notification-manager/notification_api/services/notifications/notificationconfig.py
- notification-manager/notification_api/services/notifications/notificationuser.py
- request-management-api/migrations/versions/93566cbde728_.py
- request-management-api/request_api/auth.py
- request-management-api/request_api/resources/foirecord.py
- request-management-api/request_api/services/recordservice.py
- request-management-api/wsgi.py
Changes made to the records
Restitching
Error handling and new Notification
Add triggered user part of notification
> #3547 changes to dev-marshal

- testing/foi-qa-automation/Object Repository/Page_foi.flow/form/assignee dropdown/Page_ABC-2099-14402/li_Intake, FOI.rs
- testing/foi-qa-automation/Object Repository/Page_foi.flow/form/assignee dropdown/li_assignee user option.rs
- testing/foi-qa-automation/Scripts/divisional tracking/foi-test-divisional-tracking-comments/Script1643832217318.groovy
- testing/foi-qa-automation/Scripts/divisional tracking/foi-test-divisional-tracking/Script1642714109105.groovy
- testing/foi-qa-automation/Scripts/form/foi-test-assign-to-processing/Script1644863520176.groovy
- testing/foi-qa-automation/Scripts/helper/foi-test-verify-next-assignee/Script1644612925457.groovy
- testing/foi-qa-automation/Scripts/ministry view/foi-test-ministry-new-request-received/Script1641423177207.groovy
- testing/foi-qa-automation/Scripts/queue/foi-test-filter-my-requests/Script1640221486275.groovy
- testing/foi-qa-automation/Scripts/queue/foi-test-filter-watching-requests/Script1640221467666.groovy
- testing/foi-qa-automation/Scripts/state changes/call for records/foi-test-call-for-records-to-review/Script1642537592713.groovy
- testing/foi-qa-automation/Scripts/state changes/closed/foi-test-deduplication-to-closed/Script1643741234370.groovy
- testing/foi-qa-automation/Scripts/submit/foi-test-save-request-form-navigate-away/Script1640380016267.groovy
- testing/foi-qa-automation/Scripts/submit/foi-test-save-request-form/Script1640375096408.groovy
- testing/foi-qa-automation/Test Cases/helper/foi-test-verify-next-assignee.tc
- testing/foi-qa-automation/Test Suites/foi-test-create-request-and-request-queue.ts
> #3587 updated scripts

- forms-flow-web/src/apiManager/services/FOI/foiAdminServices.js
- forms-flow-web/src/apiManager/services/FOI/foiMasterDataServices.js
- forms-flow-web/src/components/FOI/Admin/Admin.jsx
- forms-flow-web/src/components/FOI/Admin/Divisions/Divisions.jsx
- request-management-api/request_api/models/ProgramAreaDivisions.py
Added Toasts for success/error Messages
> Added Toasts for success/error Messages

- request-management-api/request_api/resources/foirecord.py
- request-management-api/request_api/schemas/foirecord.py
- request-management-api/wsgi.py
Change Details:
- Changes to increase the length of filename in schema to 500.
- Additional condition to eliminate JWT error
- Remove print statements.
Unit Test cases executed:
- Create a request
- State transition to CFR
- Upload the record with filename of length 421 of type .pdf and ensure the conversion is successful.
- Upload the record with filename of length 421 of type .docx and ensure the conversion is successful.
> Dev marshal st 3560

- forms-flow-web/src/components/FOI/customComponents/FileUpload/util.js
Fix for records upload - filetype case fix
> Fix for records upload - filetype case

- forms-flow-web/package-lock.json
- request-management-api/request_api/resources/foiflowmasterdata.py
Critical issues fixed :
- Prototype pollution in webpack loader-utils
- Insufficient validation when decoding a Socket.IO packet
- ejs template injection vulnerability
Tested all the functionalities in DEV : 
- State changes
- Attachment uploads
- CFR forms
- Emails
- Extensions
- Divisions
- Restricted Requests
> Dependabot Fixes

- forms-flow-web/src/components/FOI/customComponents/Records/index.js
Changes to change the label of duplicate count in Records.
Unit Testing
- Create a request
- State Transition
- Records : Conversion, Deduplication & Stitching
> Dev marshal st 3536

- testing/foi-qa-automation/Object Repository/Page_foi.flow/attachment/i_test2.docx_fas fa-times-circle foi-file-close.rs
- testing/foi-qa-automation/Object Repository/Page_foi.flow/attachment/li_uploaded attachment 1.rs
- testing/foi-qa-automation/Object Repository/Page_foi.flow/attachment/span_test2.docx.rs
- testing/foi-qa-automation/Scripts/attachments/foi-test-attachment-modal-behaviour/Script1641508208777.groovy
- testing/foi-qa-automation/Scripts/helper/foi-test-state-change-attachment-modal-ministryview/Script1681326693353.groovy
- testing/foi-qa-automation/Scripts/helper/foi-test-state-change-attachment-modal/Script1642709959797.groovy
> # Fixes to attachment log scripts

- forms-flow-web/src/components/FOI/customComponents/Records/index.js
- forms-flow-web/src/components/FOI/customComponents/Records/util.js
records sorted based on lastmodified asc
attachments alone sorted based on lastmodified asc
append attachments just after the parent record to arrange it properly
> Download for Harms message updated

- forms-flow-web/src/components/FOI/customComponents/Records/index.js
- forms-flow-web/src/components/FOI/customComponents/Records/util.js
including the multilevel attachments order
> Harms attachment sort and position updates

- request-management-api/request_api/services/events/legislativedate.py
- request-management-api/request_api/services/recordservice.py
> fix last modified date for replaced records

- forms-flow-web/src/components/FOI/FOIRequest/FOIRequestHeader/index.js
- forms-flow-web/src/components/FOI/customComponents/StateDropDown.js
- request-management-api/migrations/versions/eea7ea4d60ac_.py
- request-management-api/request_api/models/FOIMinistryRequests.py
- request-management-api/request_api/models/FOIRawRequests.py
Fixes related to Peer Review state
> Fixes related to Peer Review state

- forms-flow-web/src/components/FOI/customComponents/Records/index.js
Added onClick prevent default to stop tooltip to be clickable (and keep on hover properties). Tooltip was causing meunitem to be clickable (even when disabled) leading to bugs. Adjusted code to halt clicking of menuitem.
> Ticket 3903. Adjustment/Fix

- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/util.tsx
- request-management-api/request_api/services/email/templates/templateservice.py
- request-management-api/request_api/services/external/keycloakadminservice.py
- request-management-api/request_api/services/foirequest/requestservicegetter.py
Changes made:
- Updated the email template in S3
- Added backend and frontend changes to accommodate group email.
> Added group email to the email template

- forms-flow-web/src/components/FOI/Admin/Divisions/Divisions.jsx
- forms-flow-web/src/components/FOI/customComponents/Attachments/AttachmentModal.js
> Dev rq 4292

- forms-flow-web/src/components/FOI/Dashboard/Ministry/Queue.js
- forms-flow-web/src/components/FOI/Dashboard/utils.js
- forms-flow-web/src/components/FOI/customComponents/ConfirmationModal/util.js
- request-management-api/request_api/models/FOIMinistryRequests.py
- request-management-api/request_api/services/foirequest/requestservicegetter.py
- request-management-api/request_api/services/requestservice.py
- request-management-api/request_api/utils/enums.py
> Revert "#4362 - Scanning, Tagging  Clock Stop"

- request-management-api/request_api/services/events/payment.py
- request-management-api/request_api/services/events/section5pending.py
**Revert this change before deploying to prod, after testing is done**
> 8.4.5 - Change notification times for testing

- request-management-api/request_api/services/requestservice.py
pushing the changes directly to test.
> Dev dv 4702

- forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- forms-flow-web/src/components/FOI/FOIRequest/OIPCDetails/oipcHook.js
> Bug fix. Selection of no review flag removes all oipcs even if flag goes back to oipc review

- forms-flow-web/src/apiManager/httpRequestHandler/index.js
- forms-flow-web/src/components/FOI/FOIRequest/ApplicantProfileModal.js
- request-management-api/request_api/models/FOIRawRequests.py
- request-management-api/request_api/models/FOIRequestApplicants.py
- request-management-api/request_api/services/applicantservice.py
> Bug fixes - Test marshal rq 4758

- request-management-api/request_api/models/FOIRawRequests.py
- request-management-api/request_api/services/unopenedreportservice.py
> fix env data type issue

- forms-flow-web/src/components/FOI/FOIRequest/ApplicantProfileModal.js
- forms-flow-web/src/components/FOI/customComponents/Records/index.js
PR to Test marshal for removing debug code and bug fix
> PR to Test marshal for removing debug code and bug fix

- request-management-api/request_api/models/FOIRawRequests.py
- request-management-api/request_api/services/unopenedreportservice.py
> show fee amount even if fee not paid

- forms-flow-web/src/components/FOI/customComponents/Records/util.js
make sure harms also sort by modified date then filename
> make sure harms also sort by modified date then filename

- request-management-api/request_api/resources/request.py
- request-management-api/request_api/services/unopenedreportservice.py
- request-management-api/requirements.txt
run unopened report with async call
> run unopened report with async call

- request-management-api/request_api/models/UnopenedReport.py
- request-management-api/request_api/services/unopenedreportservice.py
> use bulk insert for unopened report table

- forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- forms-flow-web/src/constants/FOI/axisSyncDisplayFields.js
- request-management-api/request_api/models/FOIRequestApplicants.py
FOIMOD-2956: sync axisapplicantid for ongoing requests
> FOIMOD-2956: sync axisapplicantid for ongoing requests

- .github/workflows/zap-scan-dev.yml
FOIMOD-3026: upgarde libraries: Node.js 16 actions are deprecated
> FOIMOD-3026: upgarde libraries: Node.js 16 actions are deprecated

- forms-flow-web/src/components/FOI/customComponents/Records/index.js
- request-management-api/request_api/models/ProgramAreaDivisions.py
1. handle the case the type is an empty string
2. added missing trackingid compare
3. bug fix, ministry user could not edit divisions for cfd personal
> Bug fixes for FOIMOD-3044

- request-management-api/request_api/models/FOIMinistryRequests.py
[FOIMOD-3104](https://citz-imb.atlassian.net/browse/FOIMOD-3104)
- Fixed Request Removal from Queue with Ongoing OIPC Reviews
- Fixed Request Not Appearing in the Appropriate Request Queues
[FOIMOD-3104]: https://citz-imb.atlassian.net/browse/FOIMOD-3104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FOIMOD-3104] OIPC Review error

- request-management-api/request_api/models/FOIMinistryRequests.py
[FOIMOD-3104](https://citz-imb.atlassian.net/browse/FOIMOD-3104)
It's working as expected in DEV, so it will push it to the main branch.
[FOIMOD-3104]: https://citz-imb.atlassian.net/browse/FOIMOD-3104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FOIMOD-3104] bug fixes to main

- axisintegrationapi/MCS.FOI.AXISIntegration/MCS.FOI.AXISIntegration.DAL/RequestsDA.cs
- forms-flow-web/src/components/FOI/FOIRequest/utils.js
- request-management-api/request_api/schemas/foirequestwrapper.py
1. axis sync not getting correct axis page count
2. axis sync set recordspagecount to 0
> PR to main for page count bug fix for Release 9.8

- forms-flow-web/src/components/FOI/customComponents/StateDropDown.js
[FOIMOD-3087](https://citz-imb.atlassian.net/browse/FOIMOD-3087)
- Added filter to remove "Records Ready for Review" for non-MCF users
[FOIMOD-3087]: https://citz-imb.atlassian.net/browse/FOIMOD-3087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FOIMOD-3087] Deduplication flow state bug fixes

- forms-flow-web/src/components/FOI/customComponents/Comments/CommunicationUploadModal.js
- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/index.scss
- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/index.tsx
> Revert "3968 - Add New correspondence dropdown button"

- forms-flow-web/src/components/FOI/customComponents/Records/index.js
Hide edit button on record page for IAO members for CFD personal requests
> Small bug fixes for CFD personal tags

- forms-flow-web/src/components/FOI/Admin/Divisions/divisions.scss
- forms-flow-web/src/components/FOI/FOIRequest/ExtensionDetails/extensionscss.scss
- forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/Divisions/ConfirmModalDivision.js
- forms-flow-web/src/components/FOI/FOIRequest/foirequest.scss
- forms-flow-web/src/components/FOI/customComponents/Comments/CommunicationUploadModal.js
- forms-flow-web/src/components/FOI/customComponents/ConfirmationModal/confirmationmodal.scss
- forms-flow-web/src/components/FOI/customComponents/ConfirmationModal/index.js
- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/PreviewModal.tsx
- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/index.scss
- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/index.tsx
- forms-flow-web/src/components/FOI/customComponents/Records/index.js
- forms-flow-web/src/components/FOI/customComponents/UnsavedModal/index.js
1)CTE Secondary colors
2)Bug fix on state dropdown border introduced as part of previous communications PRs
> CTE Secondary colors and other bug fix on state dropdown

- forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- request-management-api/request_api/schemas/foirequestwrapper.py
- request-management-api/request_api/services/foirequest/requestservicebuilder.py
- request-management-api/request_api/services/foirequest/requestservicegetter.py
Fix for FOIMOD-3285 - Page Count on Closed Request Changing to 0
> FOIMOD-3285 - Page Count on Closed Request Changing to 0

- forms-flow-web/src/apiManager/services/FOI/foiRecordServices.js
- forms-flow-web/src/components/FOI/FOIRequest/BottomButtonGroup/index.js
- forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/BottomButtonGroup.js
- forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/MinistryReview.js
- forms-flow-web/src/components/FOI/customComponents/Records/index.js
- request-management-api/migrations/versions/5fdd5df3d642_.py
- request-management-api/request_api/models/FOIMinistryRequests.py
- request-management-api/request_api/resources/foirequest.py
- request-management-api/request_api/schemas/foirequestwrapper.py
- request-management-api/request_api/services/foirequest/requestservicebuilder.py
- request-management-api/request_api/services/foirequest/requestservicegetter.py
> Undo "Revert "Ticket 2880 - Lock Records""

- forms-flow-web/src/components/FOI/customComponents/Attachments/AttachmentModal.js
- forms-flow-web/src/components/FOI/customComponents/Records/index.js
Bug fix for new observation in FOIMOD-2976
> Bug fix for new observation in FOIMOD-2976

- forms-flow-web/src/components/FOI/customComponents/Records/index.js
Styling + new feature where uploading is locked for minstry + scanning user
> Ticket 2880: Additional Features Added

- forms-flow-web/src/components/FOI/customComponents/Records/index.js
fix observation #7 in FOIMOD-3300
> fix observation #7 in FOIMOD-3300

- forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/MinistryReview.js
- forms-flow-web/src/components/FOI/customComponents/Records/index.js
Fixes for FOIMOD-3079- CFD Requests - Estimated Page Counts
> Fixes for FOIMOD-3079- CFD Requests - Estimated Page Counts

- forms-flow-web/src/components/FOI/customComponents/Records/MCFPersonal.js
PR to test-rook for fixing observation #1 in FOIMOD-3300
> PR to test-rook for fixing observation #1 in FOIMOD-3300

- forms-flow-web/src/components/FOI/customComponents/FileUpload/FileUploadForMCFPersonal.js
- forms-flow-web/src/components/FOI/customComponents/Records/MCFPersonal.js
Fix observations in FOIMOD-3300
> Fix observations in FOIMOD-3300

- forms-flow-web/src/components/FOI/customComponents/FileUpload/FileUploadForMCFPersonal.js
- forms-flow-web/src/components/FOI/customComponents/Records/MCFPersonal.js
Fix observation #6 and #7 in FOIMOD-2976
> Fix observation #6 and #7 in FOIMOD-2976

- forms-flow-web/src/components/FOI/customComponents/Records/MCFPersonal.js
- forms-flow-web/src/components/FOI/customComponents/Records/index.js
- request-management-api/migrations/versions/5fdd5df3d642_.py
- request-management-api/migrations/versions/d1d4f6cdfd68_cfd_personal_tags.py
Fix observation 6 & 8 in FOIMOD-2976
> Fix observation 6 & 8 in FOIMOD-2976

- forms-flow-web/src/components/FOI/customComponents/FileUpload/FileUploadForMCFPersonal.js
disable drag and drop for observation #28 in FOIMOD-3300 (observation #9 in FOIMOD-2976)
> disable drag and drop for observation #28 in FOIMOD-3300

- forms-flow-web/src/components/FOI/customComponents/Records/MCFPersonal.js
- forms-flow-web/src/components/FOI/customComponents/Records/index.js
bug fix: adding validation for required fields for editing
> bug fix: adding validation for required fields for editing FOIMOD-3393

- forms-flow-web/src/components/FOI/customComponents/Records/MCFPersonal.js
bug fix: validate division update for ministry user FOIMOD-3393
> bug fix: validate division update for ministry user FOIMOD-3393

- request-management-api/migrations/versions/1d60153653db_update_cfd_personal_sections_sorting_.py
Update cfd personal section sorting orders FOIMOD-3413
> Update cfd personal section sorting orders FOIMOD-3413

- forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- forms-flow-web/src/components/FOI/FOIRequest/utils.js
- forms-flow-web/src/components/FOI/customComponents/Comments/AddCommentField.js
- forms-flow-web/src/components/FOI/customComponents/Comments/CommentStructure.js
- forms-flow-web/src/components/FOI/customComponents/Comments/DisplayComments.js
- forms-flow-web/src/components/FOI/customComponents/Comments/Input.js
- forms-flow-web/src/components/FOI/customComponents/Comments/InputField.js
- forms-flow-web/src/components/FOI/customComponents/Comments/comments.scss
- forms-flow-web/src/components/FOI/customComponents/Comments/commentutils.js
- forms-flow-web/src/components/FOI/customComponents/Comments/index.js
- forms-flow-web/src/helper/FOI/helper.js
- request-management-api/request_api/models/FOIRawRequestComments.py
- request-management-api/request_api/models/FOIRequestComments.py
Fixes related to Edit comment types
Updated work - New ACs added on tag list.
Minor F.E styling updates and Info added
> FOIMOD-2982:Comments Tab - Type of Comments (Peer Review, Internal, General) - Fixes and new features added

- forms-flow-web/src/components/FOI/customComponents/Comments/AddCommentField.js
- forms-flow-web/src/components/FOI/customComponents/Comments/DisplayComments.js
- forms-flow-web/src/components/FOI/customComponents/Comments/InputField.js
- forms-flow-web/src/components/FOI/customComponents/Comments/comments.scss
- request-management-api/request_api/models/CommentTypes.py
- request-management-api/request_api/services/commentservice.py
- request-management-api/request_api/services/notifications/notificationuser.py
- request-management-api/request_api/services/notificationservice.py
- request-management-api/request_api/services/watcherservice.py
FOIMOD-2982 : Updated Notifications scenarios for internal and peer review type comments.
FOIMOD-3412 - 1)  Visual indicator for selected text menu options.
2) Ability to allow users to click anywhere in the textbox to start entering a comment or reply rather than clicking the first line.
> FOIMOD-2982 : Comments Tab - Type of Comments (Peer Review, Internal, General)& FOIMOD-3412:Investigate Features to Add as Part of 10.2

- forms-flow-web/src/components/FOI/customComponents/Comments/InputField.js
- forms-flow-web/src/components/FOI/customComponents/Comments/comments.scss
FOIMOD-2982 : Minor Styling update related to reply comment post button
> FOIMOD-2982:Comments Tab - Type of Comments (Peer Review, Internal, General) - styling update

- forms-flow-web/src/components/FOI/customComponents/Comments/AddCommentField.js
- forms-flow-web/src/components/FOI/customComponents/Comments/InputField.js
CSS style fix for toolbar while tag list opens.
> FOIMOD-2982- Comments Tab - Type of Comments (Peer Review, Interna, General)-CSS style fix for toolbar while tag list opens

- request-management-api/request_api/models/FOIMinistryRequests.py
Bug fix on queue search FOIMOD-3110
> Bug fix - FOIMOD-3110

- forms-flow-web/src/components/FOI/customComponents/Comments/AddCommentField.js
- forms-flow-web/src/components/FOI/customComponents/Comments/Input.js
- forms-flow-web/src/components/FOI/customComponents/Comments/InputField.js
- forms-flow-web/src/components/FOI/customComponents/ConfirmModal.js
- forms-flow-web/src/containers/Confirm.js
- request-management-api/request_api/models/FOIRawRequestComments.py
- request-management-api/request_api/models/FOIRequestComments.py
- request-management-api/request_api/services/commentservice.py
- request-management-api/request_api/services/notifications/notificationuser.py
Disable update comment type option while editing comment
Styling updates
Watcher and assignee Notification updates
> FOIMOD-2982-Comments Tab - Type of Comments (Peer Review, Internal, General)-Observation updates

- request-management-api/request_api/models/FOIRawRequestComments.py
- request-management-api/request_api/models/FOIRequestComments.py
Fix for replies not triggering a notification to the author of the parent Internal/peer review type comment.
> FOIMOD-2982-Comments Tab - Type of Comments (Peer Review, Internal, General)-Observation 20

- forms-flow-web/src/components/FOI/customComponents/Comments/AddCommentField.js
- forms-flow-web/src/components/FOI/customComponents/Comments/InputField.js
Debug Comments removed
System generated comment reply type issue fixed
> FOIMOD-2982- Comments Tab - Type of Comments (Peer Review, Internal, General)-Observation 24  fix

- request-management-api/request_api/services/notifications/notificationuser.py
> FOIMOD-2982- Comments Tab - Type of Comments (Peer Review, Internal, General)

- forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- forms-flow-web/src/components/FOI/customComponents/Comments/AddCommentField.js
- forms-flow-web/src/components/FOI/customComponents/Comments/DisplayComments.js
- forms-flow-web/src/components/FOI/customComponents/Comments/Input.js
- forms-flow-web/src/components/FOI/customComponents/Comments/InputField.js
- forms-flow-web/src/components/FOI/customComponents/Comments/commentutils.js
- forms-flow-web/src/helper/FOI/helper.js
FOIMOD-2982-Removed commented code to rebuild web to reflect the config change for REACT_APP_DOCREVIEWER_WEB_URL value in configmap.
> FOIMOD-2982-Removed commented code

- forms-flow-web/src/components/FOI/customComponents/Comments/CommentStructure.js
Applicant correspondence fix with new comment types.
> FOIMOD-2982-Comments Tab - Type of Comments (Peer Review, Internal, General)-Applicant correspondence fix

- request-management-api/migrations/versions/3a2ffb0af202_.py
- request-management-api/migrations/versions/719e5289e6f8_.py
Migration script adjustment to fix migration error in test-marshal (2 heads)
> Ticket 2646: Main <> Test-Marshal Merge (Migration Script Adjustment)

- historical-search-api/request_api/models/factRequestDetails.py
> added oipc no filter for historical search

- request-management-api/migrations/versions/1bda7f7bae57_update_active_templates.py
- Intake/Acknowledgment Letters
- PB Extension templates 
- OIPC Extension Templates 
- First and Subsequent OIPC Time Extension
- Generic Cover Email
> FOIMOD-3674 Hide templates

- forms-flow-web/src/components/FOI/customComponents/Fees/Tabs/ApplicationFeeTab.tsx
- forms-flow-web/src/components/FOI/customComponents/Fees/Tabs/ReceiptField.tsx
> Intake Updates - Update ReceiptField

- forms-flow-web/src/components/FOI/Dashboard/IAO/KeywordSearch/ActionContext.js
- forms-flow-web/src/components/FOI/Dashboard/IAO/KeywordSearch/DataGridKeywordSearch.js
- forms-flow-web/src/components/FOI/Dashboard/IAO/KeywordSearch/KeywordSearchFooter.js
- forms-flow-web/src/modules/FOI/foiRequestsReducer.js
1) Keywords to be searched updated to check whole word in solr added "". 
2) Go to records not clickable on any other pages other than the first page.
> FOIMOD-3638- Fixes

- forms-flow-web/src/components/FOI/FOIRequest/AxisDetails/AxisDetails.js
- forms-flow-web/src/components/FOI/customComponents/RequestFlag.js
- forms-flow-web/src/components/FOI/customComponents/requestflag.scss
- request-management-api/requirements.txt
- Added request ID validation for a consult  
- Checked for duplicate IDs  
- Reverted Tornado version, which affects notifications
> FOIMOD-3774 changed request id validation

- integrationapi/MCS.FOI.Integration/MCS.FOI.Integration.API/appsettings.Development.json
> debugging github ci/cd workflow

- .github/workflows/template-api-cd.yml
- integrationapi/MCS.FOI.Integration/MCS.FOI.Integration.API/appsettings.json
> apply the ubuntu fix by Milos

- forms-flow-web/src/apiManager/services/FOI/foiCorrespondenceServices.js
- forms-flow-web/src/apiManager/services/FOI/foiMasterDataServices.js
- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/DocEditor.tsx
- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/index.tsx
1. add username to doc editor
2. disable track changes by default
3. disable auto focus to avoid loop issue on focus calls
4. remove debugging code
> add username to doc editor

- forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/CommunicationStructure.jsx
- request-management-api/request_api/services/email/templates/templateservice.py
1. send email issue
2. template name not showing
> bug fixes:

- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/DocEditor.tsx
- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/index.tsx
1. remove template header
2. bug fix: save template name when save/edit draft
3. disable/enable doc editor auto focus to fix loop focus call issue
> Bug fixes and feature update

- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/PreviewModal.tsx
- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/index.tsx
- request-management-api/request_api/services/communicationwrapperservice.py
- request-management-api/request_api/services/paymentservice.py
- request-management-api/request_api/services/requestservice.py
1. fix payment url issue
2. remove debugging code
> Fix payment url issue

- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/index.tsx
- request-management-api/request_api/services/communicationwrapperservice.py
- request-management-api/request_api/services/external/bpmservice.py
1. remove debugging code
2. save correct type
3. save correct templatetype
4. fix save pdf when there is no email
5. add missing return in api
> Test marshal rq foimod 3657

- forms-flow-web/src/services/UserService.js
This PR fixes multiple Keycloak initializations by introducing a singleton pattern using keycloakInitialized and keycloakInitPromise.
> [FOIMOD-3811] : Prevent multiple Keycloak initializations  

- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/PreviewModal.tsx
> Revert "3657 - observation 10"

- request-management-api/request_api/models/FOIRawRequests.py
Advanced search now correctly retrieves phased releases.
> Release 17.0 (Phased Release): Advanced Search Fix

- .github/workflows/forms-flow-web-cd.yml
> sync ubuntu fix

- forms-flow-web/src/constants/FOI/enum.js
trigger ubuntu fix by making small updates:
add zip file
> trigger ubuntu fix by making small updates

- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/CommunicationStructure.jsx
- forms-flow-web/src/components/FOI/customComponents/ContactApplicant/index.scss
This pull request improves the security and isolation of correspondence content rendered in the ContactApplicant component. The main changes focus on sanitizing user-generated HTML to prevent style injection and updating CSS to contain and reset styles within correspondence sections.
**Security and HTML sanitization:**
* Integrated `DOMPurify` to sanitize `correspondence.text`, explicitly forbidding `style` tags and attributes to prevent malicious or unintended CSS from affecting the application. [[1]](diffhunk://#diff-6b615de8a902ff34beefb15acceb977abd819052bbeb1da06a9e4b1cfc74cc70R34) [[2]](diffhunk://#diff-6b615de8a902ff34beefb15acceb977abd819052bbeb1da06a9e4b1cfc74cc70L100-R105)
**CSS containment and style isolation:**
* Updated `.commenttext` class in `index.scss` to use CSS …
> Release 20.0 (Application Correspondence: Bug Fix (Observation #145)

- forms-flow-web/src/components/FOI/FOIRequest/OpenInformation/Publication/OpenInfoPublication.tsx
> Release 21 (OpenInformation): Modal text adjustments.
