bcgov/foi-flow

- .sonarcloud.properties
This should not trigger a test deploy as the file isn't in the watched folders.
File must be in root dir as per SonarCloud
> SonarCloud source properties file

- .sonarcloud.properties
Copying and pasting is normal and unavoidable with
tests - it's only bad in application code.
> Exclude test files in scanning for bugs/copy-paste

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/ExtensionDetails/AddExtensionModal.js
- apps/forms-flow-ai/forms-flow-web/src/helper/FOI/helper.js
There was a bug in calculating the previous extended date on the extension modal by using addBusinessDays with a negative number to subtract business days which produced wrong results due to the reconcilePublicHolidays method. I added two methods in the helper.js to subtract business days and used them instead
> Fix subtract business days calculation

- request-management-api/request_api/resources/request.py
Hot Fix:
To resolve save failure for scenario : Saving an unopened request with team name only.
Sanity Testing:
Create new request with team name only
Update request
Change states Intake in progress -> Open -> call for records
Watch /Unwatch
Add comments
> Changes to resolve save failures for request with team name only.

- apps/forms-flow-ai/forms-flow-web/src/apiManager/services/FOI/foiMasterDataServices.js
- apps/forms-flow-ai/forms-flow-web/src/apiManager/services/FOI/foiRequestServices.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/IAO/Queue.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Dashboard/MinistryDashboard.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/ExtensionDetails/ActionContext.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/MinistryReview.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/RequestHeader.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/MinistryReview/utils.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/Header/FOIHeader.js
Fixes for :
- Two calls get triggered for /dashboard pagination . Avoid duplicate call.
- There is no need to call the endpoint /intake team with the new approach of dashboard (2 calls)
> Fix double and unnecessary calling of API endpoints 

- apps/forms-flow-ai/forms-flow-web/src/apiManager/services/FOI/foiRequestServices.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/AxisDetails/AxisDetails.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
Contains fix for the issue: Currently unable to assign myself as a user to a request before I have synced an AXIS number #1903 .
**ACs: All Passed**
**Sanity Tests Executed:**
Tested creating new request - both personal and general. Made sure all required fields are persisting data and non-mandatory fields are persisting with and with out data.
Tested state transitions and assignments, Watchers - INTAKE IN PROGRESS to CFR.
Tested login with MINISTRY VIEW with Minis. COORDIANTOR l and did state transitions.
Tested submission of  PERSONAL and GENERAL Requests from Angular App. LOCALLY.
Tested attachments, comments, notifications.
Tested Axis Sync and #1903 .
> Assigning myself to a request and syncing with AXIS (#1903)

- request-management-api/request_api/models/FOIRawRequests.py
Fix the bug in advanced search #2001:
Cannot sort by received date for unopened requests
> Bug fix: advanced search #2001

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
Axis Sync warning is still showing after the Sync.(#2034)
**ACs: Passed**
**Tests Executed:**
Tested syncing a new request with AXIS Id.
Tried Editing the fields and syncing again and the banner disappears if nothing to sync.
> Axis Sync warning is still showing after the Sync (#2034)

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/AdditionalApplicantDetails.js
**Description :** 
PHN Information is getting missed on Personal FOI Request (#2048).
Test Executed:
Tested creating new request - both personal and general. Made sure PHN value is getting saved and is displaying.
> PHN Information is getting missed on Personal FOI Request (#2048)

- apps/forms-flow-ai/forms-flow-web/src/helper/FOI/helper.js
do not subtract in late case, since endDate is returning one day before due date
> take ceil in late case since no of days is negative

- request-management-api/request_api/services/events/extension.py
Use case: Generate request history for a reason and extension days changes for states approved or denied.
Sanity Test:
1. Create request using "Sync with Axis"
2.  Create extension
3. Delete extension
4. Update extension
5. Validate notifications for extensions
6.  State transition 
7. Watch/Unwatch changes
Additional Changes:
Code reusability and naming conventions applied.
> Changes to generate request history for reason and extension days for approved and denied status.

- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/AxisDetails/AxisSyncModal.js
- apps/forms-flow-ai/forms-flow-web/src/components/FOI/FOIRequest/FOIRequest.js
- request-management-api/request_api/models/FOIRequestComments.py
- request-management-api/request_api/services/events/extension.py
- request-management-api/request_api/services/eventservice.py
Description:
Fix for Previous comments & notifications not getting cleared while syncing extensions from Axis #2759.
Comments and notifications will be generated for each of the axis approved/denied extensions.
N.B. : Moved the method for deleting previous comments/notifications to outside of the extension loop in B.E.
> Previous comments & notifications not getting cleared while syncing extensions from Axis#2759

- request-management-api/request_api/models/FOIRequestComments.py
- request-management-api/request_api/services/events/extension.py
- request-management-api/request_api/services/eventservice.py
Description : 
Query for deleting existing extension comments wasn't working in DEV but working in local. It was filtering the ministry id of comments using IN which apparently didn't work in DEV,TEST. Updated the filter query with equals.
> Fix-Query updated

- forms-flow-web/src/components/FOI/customComponents/CFRForm/index.tsx
- request-management-api/request_api/services/events/cfrfeeform.py
Show two places after the decimal for system generated comment.
Refund Amount field should be editable in any state if  form is Approved.
> Updates to #2776 and #2769

- forms-flow-web/src/components/FOI/FOIRequest/AxisDetails/AxisSyncModal.js
Minor fix on axis sync modal when all linked requests are removed from axis. 
Issue : When all linked requests in axis are removed from an already synced request. Now the banner is showing up but the Modal is not shown. Instead show the modal and show Linked requests as empty.
> Minor fix on axis sync modal when all linked requests are removed from axis

- forms-flow-web/src/constants/FOI/statusEnum.js
It looks like there isn't anything else that needs to be updated (eg. no corresponding enums on the backend) - please double check this.
> 4434-Add 'Consult' attachment tag

- request-management-api/request_api/resources/foiadmin.py
- request-management-api/request_api/resources/foicfrfee.py
- request-management-api/request_api/resources/foicomment.py
- request-management-api/request_api/resources/foidocument.py
- request-management-api/request_api/resources/foiemail.py
- request-management-api/request_api/resources/foiextension.py
- request-management-api/request_api/resources/foinotification.py
- request-management-api/request_api/resources/foipayment.py
- request-management-api/request_api/resources/foirecord.py
- request-management-api/request_api/resources/foirequest.py
- request-management-api/request_api/resources/foiwatcher.py
- request-management-api/request_api/resources/foiworkflow.py
- request-management-api/request_api/services/rawrequestservice.py
- request-management-api/request_api/services/workflowservice.py
- request-management-api/request_api/tracer.py
- request-management-api/request_api/utils/redispublisher.py
Python 3 exceptions do not have a message attributes. See [PEP 352](https://www.python.org/dev/peps/pep-0352/) for more details.
Please see corresponding docreviewer PR here: https://github.com/bcgov/foi-docreviewer/pull/560
> Ticket 4539. Fix/Adjustment to exception handling in request-management api

- request-management-api/request_api/models/FOIRawRequestNotifications.py
- request-management-api/request_api/models/FOIRawRequests.py
- request-management-api/request_api/models/FOIRequestNotificationUsers.py
- request-management-api/request_api/models/FOIRequestNotifications.py
- request-management-api/request_api/services/events/assignment.py
- request-management-api/request_api/services/events/cfrdate.py
- request-management-api/request_api/services/events/cfrfeeform.py
- request-management-api/request_api/services/events/divisiondate.py
- request-management-api/request_api/services/events/email.py
- request-management-api/request_api/services/events/extension.py
- request-management-api/request_api/services/events/legislativedate.py
- request-management-api/request_api/services/events/payment.py
- request-management-api/request_api/services/events/section5pending.py
- request-management-api/request_api/services/events/state.py
- request-management-api/request_api/services/eventservice.py
- request-management-api/request_api/services/notificationservice.py
1. NotificationTypeId was saving as null
2. advanced search with raw request closed was not working
3. removed unnecessary logs
> Fixes to notification and advanced serach

- request-management-api/request_api/models/FOIRawRequests.py
This fixes the bug of request being listed in all members of processing team; if the request belongs to processing team.
Unit Testing:
1. Create a request
2. Assign request between different groups & verify the dashboard queue (Before open)
3. Open the request 
4. Verify the ministry queue
> 4929 (Bug fix) Changes to validate user group (before open)

- request-management-api/request_api/models/FOIMinistryRequests.py
[FOIMOD-3104](https://citz-imb.atlassian.net/browse/FOIMOD-3104)
- This query utilizes a subquery to select distinct records based on foiministryrequest_id, grouping by foiministryrequestversion_id. It then returns the maximum outcomeid if all outcomeid values are non-null; otherwise, it returns null. This ensures that we capture unique records while accurately reflecting the status of the outcomeid field.
[FOIMOD-3104]: https://citz-imb.atlassian.net/browse/FOIMOD-3104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FOIMOD-3104] Requests Queues Bug Fix

- forms-flow-web/src/components/FOI/customComponents/FileUpload/FileUploadForMCFPersonal.js
- request-management-api/migrations/versions/06283c0685fb_update_cfd_personal_tags.py
1. New migration file for updating filetype and sections FOIMOD-3397
2. fix observation: enable drag & drop FOIMOD-3300
> PR to TEST: New migration file for updating filetype and sections FOIMOD-3397

- forms-flow-web/src/components/FOI/customComponents/Attachments/AttachmentModal.js
- forms-flow-web/src/components/FOI/customComponents/FileUpload/FileUploadForMCFPersonal.js
- forms-flow-web/src/components/FOI/customComponents/Records/MCFPersonal.js
- forms-flow-web/src/components/FOI/customComponents/Records/index.js
- forms-flow-web/src/constants/FOI/enum.js
- request-management-api/migrations/versions/06283c0685fb_update_cfd_personal_tags.py
- request-management-api/migrations/versions/1d60153653db_update_cfd_personal_sections_sorting_.py
Reduce # of popular sections to 20
> Sync bug fixes on main to dev

- forms-flow-web/src/components/FOI/customComponents/Comments/AddCommentField.js
- forms-flow-web/src/components/FOI/customComponents/Comments/InputField.js
- forms-flow-web/src/components/FOI/customComponents/Comments/comments.scss
- request-management-api/request_api/models/FOIRawRequestComments.py
- request-management-api/request_api/models/FOIRequestComments.py
- request-management-api/request_api/resources/foicomment.py
- request-management-api/request_api/schemas/foicomment.py
- request-management-api/request_api/services/commentservice.py
- request-management-api/request_api/services/events/attachment.py
- request-management-api/request_api/services/notifications/notificationuser.py
- request-management-api/request_api/services/notificationservice.py
FOIMOD-3412 - Shortcuts added
FOIMOD-2982 - Fixed issue with state transitions
> FOIMOD-3412 and FOIMOD-2982 : Comments Tab - Type of Comments (Peer Review, Internal, General) fixes

- forms-flow-web/src/components/FOI/customComponents/Comments/InputField.js
- request-management-api/request_api/models/FOIRawRequestComments.py
- request-management-api/request_api/models/FOIRequestComments.py
- request-management-api/request_api/schemas/foicomment.py
Update on Observation 9 - Comment replies should have the same type as the parent comment and if the parent comment type is edited it should update reply comment types as well
> FOIMOD-2982- Comments Tab - Type of Comments (Peer Review, Internal, General) - Observation 9 fix

- forms-flow-web/src/components/FOI/customComponents/Comments/InputField.js
- forms-flow-web/src/components/FOI/customComponents/Comments/index.js
- forms-flow-web/src/components/FOI/customComponents/ConfirmModal.js
- forms-flow-web/src/helper/FOI/helper.js
- request-management-api/request_api/models/FOIRawRequestComments.py
- request-management-api/request_api/models/FOIRequestComments.py
- request-management-api/request_api/services/commentservice.py
- request-management-api/request_api/services/notifications/notificationuser.py
- request-management-api/request_api/services/watcherservice.py
Updates on Observation 9,11,12, 17
> FOIMOD-2982-Comments Tab - Type of Comments (Peer Review, Internal, General)-New Observation fixes

- request-management-api/request_api/schemas/foirequestwrapper.py
- request-management-api/request_api/services/foirequest/requestservicebuilder.py
Adjusted backend cod/logic for iao users making foi request changes (new request ornew versions) in regards to records page count data. Client no longer sends recordspagecount data when requests are updated and created by IAO, instead BE and DB call is done in requestservice to get the latest recordspagecount from the latest ministry request (which was generated by the page count calculator service).
From my understanding, the page count calculator service should solely adjust and update the recordspagecount field in a foi request.
> Ticket 3467 - Incorrect page count (recordspagecount) bug fix

- forms-flow-web/src/apiManager/services/FOI/foiKeywordSearchServices.js
This PR fixes a bug where httpGETRequest was receiving an invalid params argument (a string instead of an object), causing Axios to throw a TypeError: target must be an object.
> fix - ensure httpGETRequest receives valid params to prevent Axios TypeError
